# Generated by Django 3.2.16 on 2023-03-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20230323_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='dates_to_drop',
            new_name='model_details',
        ),
    ]
