# Generated by Django 3.2.16 on 2023-03-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_rename_dates_to_drop_case_model_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='model_details',
            field=models.JSONField(null=True),
        ),
    ]
